blank_issues_enabled: false
contact_links:
  - name: RACELANDSHOP Issue tracker
    url: https://github.com/racelandshop/integration/issues
    about: For issues and feature requests related to RACELANDSHOP
